### ISSUE TITLE
Monthly/weekly hours by project summary does't add the hours instead shows individual entries

### ISSUE THREAD

**Issue by paul-szczepanek-arm** [Baralga/baralga#67]
When I select the week/month hours by project tab, instead of the hours added up per project I can see the individual stretched of time I have logged.

![baralga](https://user-images.githubusercontent.com/33840200/111449266-23330880-8707-11eb-88bd-dc81b52558a5.jpg)

If I restart baralga it will show the summary correctly but if I change the view and go back it will again show individual stretches instead of the summed up hours.

version 1.8.5, same under 1.9.4

**Comment by MBernhard** [comment]
This functionality is working for me correctly under v1.9.4 Portable (Windows 10).
When selecting "Hours by project" in the "Month" view, all project times are correctly accumulated.

**Comment by paul-szczepanek-arm** [comment]
Like I said, it works for me after restart. So whenever I need to see the values I have to close baralga, reopen it and the values are added up. Otherwise I get what you see in the screenshot (look at how many time "ip testing" shows up). I'm also using the 1.9.4 portable.

**Comment by stm-at-home** [comment]
Hi,

I would like to comment on this. This is a long standing and well-known (at least for me) bug. All 1.8.x versions are affected and
also the 1.9.7 version contains this bug. But it needs a prerequisite to show up. And I found a workaround so I didn't report this
error till now.

The prerequisite to trigger this bug is as follows. In the projects view sort the project hours by magnitude, i. e. in the **hours by project** tab of the project view click on the **Hours** column heading to sort by hours. A big triangle then shows up in the column heading adjacent **Hours** (in the **Project** column heading may show up a small triangle (like seen in the screen shot)). If you switch now to another day/month/year using the arrow buttons then the accumulated project times fall apart and are shown with a separate line for each entry.

The work around to avoid or repair this display in the project view is to sort by project name by clicking on the **Project** column header first to make the big triangle show up adjacent to the **Project** column header. Then you are free to switch to another day/month/year and keep the working hour sums intact.

If the accumulated project times have fallen apart already then to repair this, switch to "sort by project name" and then use the arrow buttons to go one time step back and forth. That will also repair the accumulated sums again. Then you may sort by
project time magnitude again.

So as as rule of thumb keep in mind when switching between days/months/years have the project view unsorted (state after program start (no triangle)) or sorted by project name to keep the accumulated project sums intact.

Best regards,
    Stefan

**Comment by remast** [comment]
@stm-at-home found it and fixed it. Actually this occurred on all aggregated views like hours by project, hours by quarter and so on.
